---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xebia-role
  namespace: xebia-prod
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xebia-rolebinding
  namespace: xebia-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xebia-role
subjects:
- kind: ServiceAccount
  name: xebia-sa
  namespace: xebia-prod
- kind: ServiceAccount
  name: xebia-sa
  namespace: xebia-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: xebia-prod
  name: xebia-sa

